# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

script1 = Script.create(title: '不動産屋')
Sentence.create([
  { actor: Sentence.actors[:whole], action: Sentence.actions[:message], message: '福田さん、このたびはご結婚おめでとうございます！', script: script1 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: 'どうも～、U字工事です、よろしくお願いしま〜す', script: script1 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: 'よろしくお願いします、いやあ', script: script1 },
])

script2 = Script.create(title: 'ペット')
Sentence.create([
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: 'どうも～、おめでとうございま～す！', script: script2 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:bokeru], message: 'どうも～、おめでとうございま～す、', script: script2 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:tsukkomu], message: 'いやいや、ね～、', script: script2 },
])

script3 = Script.create(title: 'おまえは変態か')
Sentence.create([
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「今日はこの不景気にもかかわらず、どこも行くとこのないお客さんに来ていただいて感謝せなあかんな」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「どこも行く所ないお客さんて失礼やろ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「冗談や。ほんでも今日はべっぴんさん多いな」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ほんまやな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「嘘つけ。昨日もそない言うてたやんか。毎日言うてまんねん。今日はべっぴんさん多いなと。心にもないことを。客商売の辛いとこですわ」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「何もかもばらしたらあかんやんか」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺は嘘をつくのがつくづくいやになってん」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「嘘も方便言うてつかなあかん時もあるねん」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「今日はほんまに、きれいな人ばっかりやな」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「見え見えやちゅうねん」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「それはそうと、君と相方になって五年。俺は常に君のことを唯一気の許せない友達と思っているんや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ちょっとまてよ。それを言うんなら、気が許せる友達って言うのと違うんかいな。気が許せないなんて言ったら、まるで俺がいつも君に対して悪いことするみたいやんか」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「ごめん、ごめん。ちょっとした言い底間違いや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ちょっとした言い間違いではすまされない間違いや」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「まあまあ、そう怒らんと。俺は君のことをいつも尊敬のまなざしで見てるんやから」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ほう。それは初耳や。どういったところを尊敬のまなざしで見てるんや」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「たとえば、小腹の空いた時など、コンビニで買い物をするときがあるやろ」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「まあ我々芸人は、舞台の合間にコンビニでちょっとした物を買うときがあるな」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「そのときの君の態度や。するどい目配りでキリッとしてるやんか」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「まあ一応われわれも芸人のはしくれやさかいな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「それと一瞬も見逃さないすばやい身のこなし」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「まあいつなんどき何があっても対応できるようにしてるつもりや」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「目星のものを見つけるや、一瞬の間にポケットに入れるあのスピードは誰にも真似でけへんわ」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:tsukkomu], message: '「ちょっとまて！　俺は万引きしとるんか」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「ごめんごめん。言い間違うた。君がポケットに入れたのは財布やった」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「待たんかい。ほんなら俺はスリか」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「冗談に決まってるやろ」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「いくら冗談でも言って良いことと悪いことがあるやろ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「それは最もだ。君がそんなことをするなんて俺はこれぽっちも不思議に思ったことがない」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ちょっとまて！それなら俺がスリをするのが当然見たいな言いかたやないか」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「全部冗談や。漫才を続けるために、仕方なしに、ほんまの事を言ってるだけや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ほんまの事違うやろ。ええかげんにしてくれや」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「悪かった。悪かった。この通り、頭下げて謝るわ」と相方の頭を下げさす。 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「それは俺の頭や。なんで俺が頭下げなあかんねん」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「誰の頭でも一緒やろ」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「一緒と違うわ。君みたいな非常識な男は知らんわ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「ほめてくれてありがとう」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「誰が褒めとんねん。怒っとんねん」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「この間、名神を走っとたら、追い越し車線をスピードの遅い車が走っとんねん」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「急に話が飛ぶねんな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「こっちはそんなスピードやったら左側の走行車線を走りんかいと思うやんか」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「まあそうやな。だいたい追い越し車線は急いでいる人が走っとるからな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺はいつも気がせくタイプやから、高速乗っても追い越し車線ばっかしや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「そんなタイプの人間けっこう多いからな」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺なんか小便に行くときも、トイレに着く前にズボンのチャック開けてるくらいイラチやねんや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ようある話や。俺もトイレに着く前にチャック開けてる時があるわ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「家でいま風呂湧かすスイッチ入れたと聞いたら、１分も経たんうちに全裸になっとるんや。全裸のままで湧くの待ってる状態や」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「いくらなんでもそれは気、早すぎや」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「そんな性格やから。俺はライトをパチパチと点滅させて、左へ移るようにうながしたんや。しかし、前の車は悠然とそのままのスピードで走っとるんや。だからライトをさらに点滅させると前の車はどないしたと思う」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「どないしよった」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「車の屋根の所に回転灯を出しよったんや。覆面パトやってん。俺はビックリしたのなんの途端に意気消沈や。仕方ないよって、前の車のスピードに合わせて走ったわいな。しばらくすると、やっと前の覆面パトが左に寄ってくれたから、そろりと追い越して行ったんや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「そりゃパトカーなら仕方ないな。それでも左に寄ってくれたからええやないか」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺はパトを追い越すとき、窓を開けてウインクして言ってやったんや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「なんて言ったんや」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「うーんもう、いじわるって」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「おまえはおかまか。パトに色目を使いよって」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「おかまと違うけどときたま化粧するな」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「それやったらおかまやんけ」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「男が化粧したらなんでおかまや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「何のために化粧するねん」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「男を引っ掛けるためや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「やっぱりおかまやないか」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「冗談や。化粧なんかするわけあらへん」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ほっとしたわ。相方がおかまやったら厭やさかいな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「安心しろ。ときたま口紅塗るだけや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ちょっと待て。それが恐いわ」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「そんなこと本気にするな。すべて冗談で言うてへんから」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「今、どさくさにまぎれてなんて言った？　冗談違うと言ったやんか」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「大丈夫。お前をビックリさせただけや。ほんまに俺はおかまと違う。ただのホモや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「ちょっと待て！いいかげんにしてくれ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「全部うそや。お前をおちょくってただけや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「パトカーよりお前の方が意地が悪いわ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「まあそれはさて置いて、話は違うけどこの間、夜中に警官に職務質問されてな」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「なんでまた夜中に歩いっとたんや」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「なんかええもんないかと物色しとったんや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「そんなもん夜中に物色しとったら、誰でも怪しむわ。それで何を物色してたんや。まさか下着やないやろな」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「警官もお前と同じこと疑いよったねん」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「当たり前や。夜中に物色してる言うたら、大抵は泥棒に決まっとるやろ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「いろいろ聞かれてな。住まいは何処やとか、仕事は何してるねんとか、しつこいくらい聞いてきよったわ」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「当たり前や」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「仕事は漫才師やいうたら、嘘つけ、テレビで見たことないわ、言うさかい、俺も偉そうに言うたったわ」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「なんて言うたったんや」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「自慢じゃないけど一度もテレビに出たことないわって」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「まあ俺らもあんまり売れてないからしょうないけど」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「夜中に何をうろちょろしとるねん、と聞くさかい、漫才のネタを考えとるねん、と言うたら、そんな感じやなかったと言いよるねん」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「そりゃお前かて、何かを物色しとる言うとったからな。警官にもそれが分かるやろ」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「それで持ち物検査も詳しくされたが、怪しい物は何にもないよって一時間位して、やっと解放してくれたんや」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「お前がなんか、悪いことして捕まったら、俺も仕事なくなるさかい、行動にはくれぐれも気をつけてくれや」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「そないなったら、俺が飯食わせてやるがな」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「どうやって食わせてくれるねん」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「この身売ったらええだけや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「えっ？　やっぱりこっち系」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「冗談や。ところで、絶対、警官は俺を下着泥棒かなんか疑っていたんや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「警官に限らず夜中にうろちょろしてたら誰でもそない思うやろ」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺が赤やピンクや、コマネチみたいな三角巾みたいな、あんなチャラチャラした下着を狙うと思うか」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「そういわれて見ればそうやな。お前がそんな物に興味があるなんて、一度でもそんなそぶりを見せたことないからな」', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「俺が本当に狙っていたのは」', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「お前が本当に狙っていたのは」 ', script: script3 },
  { actor: Sentence.actors[:boke], action: Sentence.actions[:message], message: '「たくましい男物のパンツや」 ', script: script3 },
  { actor: Sentence.actors[:tsukkomi], action: Sentence.actions[:message], message: '「やっぱり変態やんか。もうやってられんわ」', script: script3 },
])
