import * as manzai from "./manzai";

var script = <manzai.IScript>{
  title: "自殺の止め方",
  sentences: <manzai.ISentence[]>[
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'どうもです！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'どうも～～！よろしくお願いします！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'おいおいおい、' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'ごめんごめんごめん、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'そんなに、「恋に盲目」じゃないんだからさ、マイクに当たらなくても' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いやぁ～、ねえ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'はい、アンタッチャブルです、よろしくお願いしま～す！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'お願いしま～す！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いやあ、うれしいね！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '練習の甲斐あって、きちんとね、パチパチパチパチと、ありがたいね' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ありがとうございます～！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いやでもねえ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '拍手していただけるなんて嬉しいよねえ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'ホントありがたいことよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'よくよく考えたらよ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '手とね、手のひらをバンバンぶつかり合ってるわけじゃない' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'そうよそうよ！拍手ってそういうもんだから' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'ねえ、細胞死んでるわけだから！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '死んでるよ、死んでる、死んでる！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '細胞殺してまでね' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'こいつらに拍手してあげようっていう、その根性がありがたいっていうかね～！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'ま、でも、こいつらの為に細胞殺そうと思って、手を合わせてる人はいないと思うよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'いやいや、そのぐらいの勢いありますよねえ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'いや、そこは無いと思う' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '細胞を頂いてるわけですよ、皆さんに！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '細胞頂いてるわけじゃねえ！それ表現が違うよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'ありがとうございます、ホントに、最後に笑うのはやっぱ細胞ですよ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '細胞細胞って、うるせえなお前！…冒頭から細胞細胞ってお前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ホントにねぇ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '理科の実験室かどっか行け！舞台じゃなくて～！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そうやってね、細胞が飛んできてんだから～' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '細胞じゃねえんだよ、唾液だよ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '何お前、ちょっと触っただけで、そんなによろけんの、お前' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いやホント、うれしいよ～！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うれしいけどもよ！折角「バカ爆発」っていってお前、ＤＶＤにもなるっつってんだからよぉ、お前' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そうなんですよ、ＤＶＤ…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '細胞細胞言ってる場合じゃないよ、お前' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そうやって、ＤＶＤにしていただけるっていうのが嬉しいよね！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '嬉しいよ' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ね～、僕らがデータになるわけですよ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'まあね（笑）' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'こんなねぇ、今やデータになるなんて思わないからね～、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うんうん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '高校のときなんて、データになんねえだろうなあなんて、生きてたら' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '今データになるっていうね！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'お前うっせえよ！お前、データとか細胞だとかどうでもいいわ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '嬉しいよやっぱり～！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '嬉しいけど、夢が、「将来の夢データ」っていうやついねえだろ、今までお前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '読み取ってくれるっていうね！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '読み取るとかはいいんだよ、技術者に感謝しろよお前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'ありがとうございます、ホントにね～！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '折角お客さんも来てくれてんだから、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そうそうそう、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'このままじゃお前、俺らのＤＶＤ、細胞とデータだけだぞ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ねえ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'なんか違う話もしようよ～、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いやホント嬉しいよねえ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '嬉しいよ、分かったからさあ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、でも、ホントね～、…寝てないんだよね！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'なんだよ今度は急に～（苦笑）' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ホントにもうぶっちゃけちゃおう、もうやっぱみんななんかこう、すごい心開ける相手だから、ぶっちゃけちゃうけどぉ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'おう' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '寝てない！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '俺、言いたくなかった、今日言わないって決めてたの！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'おう、じゃ言わなくてよかったよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ね、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あぁ、ぶっちゃけなくてよかったよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '泣かないし～、言わないって決めてたんだけど～' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'おう、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '言うわ、やっぱり' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '泣かないは、当たり前だろ、お前！…どのチャンスで泣こうと思ってたんだよ、お前！…なあ、教えてくれよ、その機会を！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '寝てないの、ホントに！だからボ～ッとしてんのよ、やっぱり' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '何で寝てねえんだよ、お前～！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だから、悩み事があるんですよ、僕だってね！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'お前なんかにあるかい、悩み事なんかお前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、ホントホントホント' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '寝てないってお前、いつも寝てるじゃねえかよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'いやホント寝てない！今回パッと目が覚めたら朝なんだから' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '寝てるじゃねえか、お前！パッと目が覚める前は寝てんだよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、完璧に寝てないとは言わないけど！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '完璧に寝てないじゃねえかよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ちょっとぐらい…「寝てないとか寝てない」とか、そういうこと言ってんじゃないの！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '寝てないしか言ってねえよ、お前！「寝てる寝てない」だろ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そういうことじゃなくて、悩みがあることを心配してよ、相方ならさ～！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '何だよ！じゃ、悩みってよ～、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '夢でもあんだけどぉ、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'おぅ、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'あの自殺する人を僕止めたいっていうね、悩みがあるのよ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '何それ！？' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そうそうそうそう、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'えぇ？' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そういうのがあって、ただ～、どう止めていいか分か※○△×…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'え、何？なんて伝えていいかが分かんないの、それ？' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'ちょっと今（ＤＶＤの）再生がね、…おかしくなったんだね！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あ～もう、データになってんだ、お前' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '家庭の方の…家庭のほうの問題ですから、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あ、そう' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'うん、だからね、僕はどう止めていいか分かんないんですよ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'え、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だからそれが悩みなの、どうしたら止められるのかっていうのが分かんない！だから、それを教えて欲しいの、ホントに！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'ホントにって言われてもなあ、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'お願いっ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'お願いって言われても…' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'お願い、ホント！ホント！普通のお願い！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '一生にしろよ、お前！なんで普通程度でお願いすんだよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '一生のお願いはまだ使えない、これは' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'シチュエーションがまず意味が分かんね～もん、だって、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、だからぁ！自殺しようとしてる人がいるとするじゃん、飛び降りようとしてる人目の前に見ちゃったと、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そんときに、僕、今の僕だったら何も出来ないと思うよ！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うんうん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'もう、下手すりゃ押しちゃうよ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'なんでだよ、お前！なんで何にも出来ないやつが引き出し持ってんだよ、押すほうだけは！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だからもう、「ああ、あぁあぁあぁ～！」ってなっちゃう、ホントに！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '困るよ、そんなのお前～！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だから、どうしていいかっちゅうのを教えて欲しいのよ' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '分かんねえよ、そんな…' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、それこそどう声を掛けていいか分かんないの、逝こうとしてる人を、あ～っと見て～' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うんうん' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '「何、何、最近どう！？」って…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '「最近どう！？」はまずい、最近良いことないんだから飛び降りるんだから、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: 'でしょ！でしょ！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '1番最近は聞いちゃいけないよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「えっ、ツーカー（携帯メーカー）」なんだ！？とかいっても、しょうがない' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '「ツーカーなんだ」って、なんで電話してんだ、飛び降りる前に！？飛び降りる気無いよ、そいつ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'いや、分かんないけど、どうかけていいか分かんない…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'なんで分かんねえんだ、止めたいんだったら「やめなさい！」とか言やあいいだろ、バ～ッとよ～、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'あ、「やめなさい！」ね！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'そうだよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'あ、なるほどね！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'はいはいはい' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '叩けや、お前！なんでこのまま（手を置いたまま）出してんだよお前、叩けよ！！ひらめけよ！！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめなさい！」でいいわけね！？うんうん' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: '「やめなさい！」って言やあいいんだよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめなさい！」っていうのは、疑問形じゃなくていいよね！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '当たり前だよお前！やだよ「やめなさい？」って言われてもお前、「やめなさい！」だよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめなさい！」あ～、でもちょっと待って、怖いな「やめなさい！」は' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '何でだよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '万が一だけど～、「やめなちゃい！」っていっちゃうかもしれない…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'ちゃっ…、子供相手じゃねえんだよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'すごい緊張してるわけじゃん、ビックリしてるわけじゃん、噛んじゃう可能性だってあるんだよ、それをやっぱ、極力避けたいの！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '大丈夫だよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だから、やだよ！やだ、やだよ！だって自分が自殺しようと思ってね、' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あぁ、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'テンパッてる訳じゃん！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あぁ、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'そしたら横から知らない男が来てさ、（両手を上下に広げて）「やめなちゃい！」…（両手を真横に広げて）「やめなちゃい！」…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'いや、「ちゃい！」より、このポーズのほうが気になるわ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '例えばそう来たら～、変な空気になるでしょうよ！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'そりゃあなるよ（笑）！じゃ、いいよ。「やめろ～！」とかでいいだろ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめろ～！」も「ニャロメ～！」ってこともあるだろうね' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '「ニャロメ！」はないよ！お前万が一で「やめろ！」のとこを「ニャロメ！」って言ったことあんのかよ、過去！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '無いとはいえない、無いとは言い切れない！' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'あるのかよお前、じゃあよ！！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'だから、分かんないから、そういうのを極力避けたい…' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '「やめろ！」が言えねえんだったら、何も言えない！「やめろ～！」でいいんだよ、「やめろ～！」って言えばよ～！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'あぁ～、「やめろ～！」って！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'そうそう、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめろ～！！」' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「やめろ～！」' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'うん、' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '（変なポーズで）「やめろ～！」' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'いやポーズがおかしいんだよな！？なんかそいつに向かって「ズームイン！」みたいになってるからよ！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'なんでよ～' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'いや、こんなこと（ズームイン！）されても、じゃ、自然となんか、出るだろっ！（両手を突き出しながら）「やめろっ！」って、' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: 'あ、両手！両手！？' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: 'そうそう、' },
    { actor: manzai.Actor.boke, action: manzai.Action.bokeru, message: '「やめろ～！」「やめろ～！」（アゴを突き出して）「やめろ～！」' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.tsukkomu, message: 'アゴも出てるんだって、なんかこう、挑んでるやつみたいに「やめろ！やめろやめろ！」' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '「ヘイヘイヘイ！」' },
    { actor: manzai.Actor.tsukkomi, action: manzai.Action.message, message: '「ヘイヘイヘイ！」じゃないんだよ、お前！' },
    { actor: manzai.Actor.boke, action: manzai.Action.message, message: '…' },
  ]
};

var timeline = new manzai.Timeline(script);
document.addEventListener("click", onclick);

function onclick(): void {
  if (timeline.playing) {
    timeline.play();
  } else {
    timeline.end();
    document.removeEventListener("click", onclick);
  }
}
